version: "3"
services: 
  node-app:
    nginx:
    ports:
      - "80:80"
    build: 
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: node index.js
