#same in both (dev+prod)
version: "3"
#each service is a container
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  #defines the name of container
  node-app:
    build: .
    environment:
      - PORT=3000
    #starts mongo container first
    depends_on:
      - mongo
  #defines the name
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mypw1234
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis
    
volumes:
  mongo-db:
###################################### run database with authentication
#mongosh "mongodb+srv://cluster0.u7rfa76.mongodb.net/myFirstDatabase" --apiVersion 1 --username Massimo
#pw: vwzyubqQf7TdEmug